# Generated by Django 2.2.14 on 2020-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_available_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_book',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
