# Generated by Django 2.2.14 on 2020-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200723_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_book',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
