# Generated by Django 2.2.14 on 2020-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200723_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_book',
            name='image',
            field=models.TextField(max_length=100),
        ),
    ]
