# Generated by Django 2.2.14 on 2020-07-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200723_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='available_book',
        ),
    ]
