# Generated by Django 2.2.14 on 2020-07-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_available_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='available_book',
        ),
    ]
