# Generated by Django 2.2.14 on 2020-07-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_buy_book_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_book_model',
            name='image',
        ),
        migrations.RemoveField(
            model_name='buy_book_model',
            name='price',
        ),
    ]
